# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 723e2d2c2091dbae87f7fb73a88bccac0ead3b95c41f5d74748e632bedf59cc9fe3da7d99148c6df196dfcb63543bdeae567783a01d48de117c464c80b5a6b9c

test:
  secret_key_base: 3abdc62dd09d8e3497db7b5393713c958bc743b3834e17ef4ef15b7e99608799d78774febc6eec1b8d65dc2357782831adee9c2c704aec1c20e517b4d8295a06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
